<?php

/**
 * Get all Nigerian Local Government Areas sorted alphabetically
 *
 * @return array An alphabetically sorted array of all Nigerian LGAs
 */
function getNigeriaStatesAndLGAs1()
{
    return [
        'Abaji',
        'Aba North',
        'Aba South',
        'Abadam',
        'Abak',
        'Abeokuta North',
        'Abeokuta South',
        'Abi',
        'Aboh Mbaise',
        'Abua/Odual',
        'Adavi',
        'Ado',
        'Ado Ekiti',
        'Afijio',
        'Afikpo North',
        'Afikpo South',
        'Agaie',
        'Agatu',
        'Agege',
        'Aguata',
        'Agwara',
        'Ahiazu Mbaise',
        'Ahoada East',
        'Ahoada West',
        'Ajaokuta',
        'Ajeromi-Ifelodun',
        'Ajingi',
        'Akamkpa',
        'Akinyele',
        'Akko',
        'Akoko-Edo',
        'Akoko North-East',
        'Akoko North-West',
        'Akoko South-East',
        'Akoko South-West',
        'Akpabuyo',
        'Akuku-Toru',
        'Akure North',
        'Akure South',
        'Akwanga',
        'Albasu',
        'Aleiro',
        'Alimosho',
        'Alkaleri',
        'Amuwo-Odofin',
        'Anambra East',
        'Anambra West',
        'Anaocha',
        'Andoni',
        'Aninri',
        'Aniocha North',
        'Aniocha South',
        'Anka',
        'Ankpa',
        'Apa',
        'Apapa',
        'Ardo Kola',
        'Arewa Dandi',
        'Argungu',
        'Arochukwu',
        'Asa',
        'Asari-Toru',
        'Askira/Uba',
        'Atakunmosa East',
        'Atakunmosa West',
        'Atiba',
        'Atisbo',
        'Augie',
        'Auyo',
        'Awe',
        'Awgu',
        'Awka North',
        'Awka South',
        'Ayamelum',
        'Ayedaade',
        'Ayedire',
        'Babura',
        'Badagry',
        'Bagudo',
        'Bagwai',
        'Bakassi',
        'Bakori',
        'Bakura',
        'Balanga',
        'Bali',
        'Bama',
        'Bande',
        'Barkin Ladi',
        'Baruten',
        'Bassa (Kogi)',
        'Bassa (Plateau)',
        'Batagarawa',
        'Batsari',
        'Bauchi',
        'Baure',
        'Bayo',
        'Bebeji',
        'Bekwarra',
        'Bende',
        'Biase',
        'Bichi',
        'Bida',
        'Billiri',
        'Bindawa',
        'Binji',
        'Biriniwa',
        'Birnin Gwari',
        'Birnin Kebbi',
        'Birnin Kudu',
        'Birnin Magaji/Kiyaw',
        'Biu',
        'Bodinga',
        'Bogoro',
        'Boki',
        'Boluwaduro',
        'Bomadi',
        'Bonny',
        'Borgu',
        'Boripe',
        'Bursari',
        'Bosso',
        'Brass',
        'Buji',
        'Bukkuyum',
        'Bungudu',
        'Bunza',
        'Burutu',
        'Bwari',
        'Calabar Municipal',
        'Calabar South',
        'Chanchaga',
        'Charanchi',
        'Chibok',
        'Chikun',
        'Dala',
        'Damaturu',
        'Damban',
        'Dambatta',
        'Damboa',
        'Dan Musa',
        'Dandi',
        'Dandume',
        'Dange Shuni',
        'Danja',
        'Darazo',
        'Dass',
        'Daura',
        'Dawakin Kudu',
        'Dawakin Tofa',
        'Degema',
        'Dekina',
        'Demsa',
        'Dikwa',
        'Doguwa',
        'Doma',
        'Donga',
        'Dutse',
        'Dutsi',
        'Dutsin Ma',
        'Eastern Obolo',
        'Ebonyi',
        'Edati',
        'Ede North',
        'Ede South',
        'Edu',
        'Efon',
        'Egbado North',
        'Egbado South',
        'Egbeda',
        'Egbeda',
        'Ekeremor',
        'Eket',
        'Ekiti',
        'Ekiti East',
        'Ekiti South-West',
        'Ekiti West',
        'Ekwusigo',
        'Eleme',
        'Emohua',
        'Emure',
        'Enugu East',
        'Enugu North',
        'Enugu South',
        'Epe',
        'Esan Central',
        'Esan North-East',
        'Esan South-East',
        'Esan West',
        'Ese Odo',
        'Esit Eket',
        'Essien Udim',
        'Etche',
        'Ethiope East',
        'Ethiope West',
        'Etim Ekpo',
        'Etinan',
        'Eti Osa',
        'Etsako Central',
        'Etsako East',
        'Etsako West',
        'Etung',
        'Ewekoro',
        'Ezeagu',
        'Ezinihitte',
        'Ezza North',
        'Ezza South',
        'Fagge',
        'Fakai',
        'Faskari',
        'Fika',
        'Fufore',
        'Funakaye',
        'Fune',
        'Funtua',
        'Gabasawa',
        'Gada',
        'Gagarawa',
        'Gamawa',
        'Ganjuwa',
        'Ganye',
        'Garki',
        'Garko',
        'Garun Mallam',
        'Gashaka',
        'Gassol',
        'Gaya',
        'Gayuk',
        'Gezawa',
        'Gbako',
        'Gboko',
        'Gbonyin',
        'Geidam',
        'Gembu',
        'Giade',
        'Giwa',
        'Gokana',
        'Gombe',
        'Gombi',
        'Goronyo',
        'Gubio',
        'Gudu',
        'Gujba',
        'Gulani',
        'Guma',
        'Gumel',
        'Gummi',
        'Gurara',
        'Guri',
        'Gusau',
        'Guzamala',
        'Gwagwalada',
        'Gwale',
        'Gwandu',
        'Gwaram',
        'Gwarzo',
        'Gwer East',
        'Gwer West',
        'Gwiwa',
        'Gwoza',
        'Hadejia',
        'Hawul',
        'Hong',
        'Ibadan North',
        'Ibadan North-East',
        'Ibadan North-West',
        'Ibadan South-East',
        'Ibadan South-West',
        'Ibaji',
        'Ibarapa Central',
        'Ibarapa East',
        'Ibarapa North',
        'Ibeju-Lekki',
        'Ibeno',
        'Ibesikpo Asutan',
        'Ibi',
        'Ibiono-Ibom',
        'Idah',
        'Idanre',
        'Ideato North',
        'Ideato South',
        'Idemili North',
        'Idemili South',
        'Ido',
        'Ido Osi',
        'Ifako-Ijaiye',
        'Ifedayo',
        'Ifedore',
        'Ifelodun (Kwara)',
        'Ifelodun (Osun)',
        'Ifo',
        'Igabi',
        'Igalamela-Odolu',
        'Igbo Etiti',
        'Igbo Eze North',
        'Igbo Eze South',
        'Igueben',
        'Ihiala',
        'Ihitte/Uboma',
        'Ijebu East',
        'Ijebu North',
        'Ijebu North East',
        'Ijebu Ode',
        'Ijero',
        'Ijumu',
        'Ika',
        'Ika North East',
        'Ikara',
        'Ika South',
        'Ikeduru',
        'Ikeja',
        'Ikenne',
        'Ikere',
        'Ikole',
        'Ikom',
        'Ikono',
        'Ikorodu',
        'Ikot Abasi',
        'Ikot Ekpene',
        'Ikpoba Okha',
        'Ikwerre',
        'Ikwo',
        'Ikwuano',
        'Ila',
        'Ilejemeje',
        'Ile Oluji/Okeigbo',
        'Ilesa East',
        'Ilesa West',
        'Illela',
        'Ilorin East',
        'Ilorin South',
        'Ilorin West',
        'Imeko Afon',
        'Ingawa',
        'Ini',
        'Ipokia',
        'Irele',
        'Irepo',
        'Irepodun (Kwara)',
        'Irepodun (Osun)',
        'Irepodun/Ifelodun',
        'Irewole',
        'Isa',
        'Ise/Orun',
        'Iseyin',
        'Ishielu',
        'Isiala Mbano',
        'Isiala Ngwa North',
        'Isiala Ngwa South',
        'Isin',
        'Isi Uzo',
        'Isokan',
        'Isoko North',
        'Isoko South',
        'Isu',
        'Isuikwuato',
        'Itas/Gadau',
        'Itesiwaju',
        'Itu',
        'Ivo',
        'Iwajowa',
        'Iwo',
        'Izzi',
        'Jaba',
        'Jada',
        'Jahun',
        'Jakusko',
        'Jalingo',
        'Jama\'are',
        'Jega',
        'Jema\'a',
        'Jere',
        'Jibia',
        'Jos East',
        'Jos North',
        'Jos South',
        'Kabba/Bunu',
        'Kabo',
        'Kachia',
        'Kaduna North',
        'Kaduna South',
        'Kafin Hausa',
        'Kafur',
        'Kaga',
        'Kagarko',
        'Kaiama',
        'Kaita',
        'Kajola',
        'Kajuru',
        'Kala/Balge',
        'Kalgo',
        'Kaltungo',
        'Kanam',
        'Kankara',
        'Kanke',
        'Kankia',
        'Kano Municipal',
        'Karasuwa',
        'Karaye',
        'Karim Lamido',
        'Karu',
        'Katagum',
        'Katcha',
        'Katsina',
        'Katsina-Ala',
        'Kaura',
        'Kaura Namoda',
        'Kauru',
        'Kazaure',
        'Keana',
        'Kebbe',
        'Keffi',
        'Khana',
        'Kibiya',
        'Kirfi',
        'Kiri Kasama',
        'Kiru',
        'Kiyawa',
        'Kogi',
        'Koko/Besse',
        'Kokona',
        'Kolokuma/Opokuma',
        'Konduga',
        'Konshisha',
        'Kontagora',
        'Kosofe',
        'Kaugama',
        'Kubau',
        'Kudan',
        'Kuje',
        'Kukawa',
        'Kumbotso',
        'Kumi',
        'Kunchi',
        'Kura',
        'Kurfi',
        'Kusada',
        'Kwali',
        'Kwande',
        'Kwami',
        'Kware',
        'Kwaya Kusar',
        'Lafia',
        'Lagelu',
        'Lagos Island',
        'Lagos Mainland',
        'Lamurde',
        'Langtang North',
        'Langtang South',
        'Lapai',
        'Larmurde',
        'Lau',
        'Lavun',
        'Lere',
        'Logo',
        'Lokoja',
        'Machina',
        'Madagali',
        'Madobi',
        'Mafa',
        'Magama',
        'Magumeri',
        'Mai\'Adua',
        'Maiduguri',
        'Maigatari',
        'Maiha',
        'Maiyama',
        'Makarfi',
        'Makoda',
        'Malam Madori',
        'Malumfashi',
        'Mangu',
        'Mani',
        'Maradun',
        'Mariga',
        'Markafi',
        'Marte',
        'Maru',
        'Mashegu',
        'Mashi',
        'Matazu',
        'Mayo Belwa',
        'Mbaitoli',
        'Mbo',
        'Michika',
        'Miga',
        'Mikang',
        'Minjibir',
        'Misau',
        'Moba',
        'Mobbar',
        'Mopa Muro',
        'Moro',
        'Mubi North',
        'Mubi South',
        'Mukono',
        'Musawa',
        'Mushin',
        'Nafada',
        'Nangere',
        'Nasarawa',
        'Nasarawa',
        'Nasarawa Egon',
        'Ndokwa East',
        'Ndokwa West',
        'Nembe',
        'Ngala',
        'Nganzai',
        'Ngaski',
        'Ngor Okpala',
        'Nguru',
        'Ningi',
        'Njaba',
        'Njikoka',
        'Nkanu East',
        'Nkanu West',
        'Nkwerre',
        'Nnewi North',
        'Nnewi South',
        'Nsit-Atai',
        'Nsit-Ibom',
        'Nsit-Ubium',
        'Nsukka',
        'Numan',
        'Nwangele',
        'Obafemi Owode',
        'Obanliku',
        'Obi (Benue)',
        'Obi (Nasarawa)',
        'Obi Ngwa',
        'Obio/Akpor',
        'Obokun',
        'Obot Akara',
        'Obowo',
        'Obubra',
        'Obudu',
        'Odeda',
        'Odigbo',
        'Odo Otin',
        'Odogbolu',
        'Odukpani',
        'Offa',
        'Ofu',
        'Ogba/Egbema/Ndoni',
        'Ogbadibo',
        'Ogbaru',
        'Ogbia',
        'Ogbomosho North',
        'Ogbomosho South',
        'Ogu/Bolo',
        'Ogoja',
        'Ogo Oluwa',
        'Ogori/Magongo',
        'Ogun Waterside',
        'Oguta',
        'Ohafia',
        'Ohaji/Egbema',
        'Ohaozara',
        'Ohaukwu',
        'Ohimini',
        'Orhionmwon',
        'Oji River',
        'Ojo',
        'Oju',
        'Okehi',
        'Okene',
        'Oke Ero',
        'Okigwe',
        'Okitipupa',
        'Okobo',
        'Okpe',
        'Okrika',
        'Olamaboro',
        'Ola Oluwa',
        'Olorunda',
        'Olorunsogo',
        'Oluyole',
        'Omala',
        'Omuma',
        'Ona Ara',
        'Ondo East',
        'Ondo West',
        'Onicha',
        'Onitsha North',
        'Onitsha South',
        'Onna',
        'Okpokwu',
        'Opobo/Nkoro',
        'Oredo',
        'Orelope',
        'Oriade',
        'Ori Ire',
        'Orlu',
        'Orolu',
        'Oron',
        'Orsu',
        'Oru East',
        'Oru West',
        'Oruk Anam',
        'Orumba North',
        'Orumba South',
        'Ose',
        'Oshimili North',
        'Oshimili South',
        'Oshodi-Isolo',
        'Osisioma',
        'Osogbo',
        'Oturkpo',
        'Ovia North-East',
        'Ovia South-West',
        'Owan East',
        'Owan West',
        'Owerri Municipal',
        'Owerri North',
        'Owerri West',
        'Owo',
        'Oye',
        'Oyi',
        'Oyigbo',
        'Oyo',
        'Oyo East',
        'Oyun',
        'Paikoro',
        'Pankshin',
        'Patani',
        'Pategi',
        'Port Harcourt',
        'Potiskum',
        'Qua\'an Pan',
        'Rabah',
        'Rafi',
        'Rano',
        'Remo North',
        'Rijau',
        'Rimi',
        'Rimin Gado',
        'Ringim',
        'Riyom',
        'Rogo',
        'Roni',
        'Sabon Birni',
        'Sabon Gari',
        'Sabuwa',
        'Safana',
        'Sagbama',
        'Sakaba',
        'Saki East',
        'Saki West',
        'Sandamu',
        'Sanga',
        'Sapele',
        'Sardauna',
        'Shagamu',
        'Shagari',
        'Shanga',
        'Shani',
        'Shanono',
        'Shelleng',
        'Shendam',
        'Shinkafi',
        'Shira',
        'Shiroro',
        'Shongom',
        'Shomolu',
        'Silame',
        'Soba',
        'Sokoto North',
        'Sokoto South',
        'Song',
        'Southern Ijaw',
        'Suleja',
        'Sule Tankarkar',
        'Sumaila',
        'Suru',
        'Surulere (Lagos)',
        'Surulere (Oyo)',
        'Tafa',
        'Tafawa Balewa',
        'Tai',
        'Takai',
        'Takum',
        'Talata Mafara',
        'Tambuwal',
        'Tangaza',
        'Tarauni',
        'Tarka',
        'Tarmuwa',
        'Taura',
        'Toungo',
        'Tofa',
        'Toro',
        'Toto',
        'Toungo',
        'Tsafe',
        'Tsanyawa',
        'Tudun Wada',
        'Tureta',
        'Udenu',
        'Udi',
        'Udu',
        'Udung-Uko',
        'Ughelli North',
        'Ughelli South',
        'Ugwunagbo',
        'Uhunmwonde',
        'Ukanafun',
        'Ukum',
        'Ukwa East',
        'Ukwa West',
        'Ukwuani',
        'Umuahia North',
        'Umuahia South',
        'Umu Nneochi',
        'Ungogo',
        'Unuimo',
        'Uruan',
        'Urue-Offong/Oruko',
        'Ushongo',
        'Ussa',
        'Uvwie',
        'Uyo',
        'Uzo-Uwani',
        'Vandeikya',
        'Wamako',
        'Wamba',
        'Warawa',
        'Warji',
        'Warri North',
        'Warri South',
        'Warri South West',
        'Wasagu/Danko',
        'Wase',
        'Wudil',
        'Wukari',
        'Wurno',
        'Wushishi',
        'Yabo',
        'Yagba East',
        'Yagba West',
        'Yakurr',
        'Yala',
        'Yamaltu/Deba',
        'Yankwashi',
        'Yauri',
        'Yenagoa',
        'Yola North',
        'Yola South',
        'Yorro',
        'Yunusari',
        'Yusufari',
        'Zaki',
        'Zango',
        'Zangon Kataf',
        'Zaria',
        'Zing',
        'Zurmi',
        'Zuru'
    ];
}

function getMsmeSector()
{
    return [
        'Trade and Commerce',
        'Agriculture',
        'Manufacturing',
        'Power and Energy',
        'Building And Construction',
        'Financial and insurance activities',
        'Real estate activities',
        'Education & Educational Services',
        'Health Services',
        'Accommodation and food service activities',
        'Other service activities',
        'Transportation',
        'Professional',
        'Scientific and technical activities',
        'Information and technology',
        'Administrative and support service activities',
        'Water supply',
        'Sewerage',
        'Waste management and remediation activities',
        'Arts',
        'Entertainment and recreation',
        'Electricals/Electronics'
    ];
}

function getNigeriaStatesAndLGAs()
{
    return [
        'Abia' => [
        'Aba North',
        'Aba South',
        'Arochukwu',
        'Bende',
        'Ikwuano',
        'Isiala Ngwa North',
        'Isiala Ngwa South',
        'Isuikwuato',
        'Obi Ngwa',
        'Ohafia',
        'Osisioma Ngwa',
        'Ugwunagbo',
        'Ukwa East',
        'Ukwa West',
        'Umuahia North',
        'Umuahia South',
        'Umu Nneochi'
    ],
    'Adamawa' => [
        'Demsa',
        'Fufore',
        'Ganye',
        'Girei',
        'Gombi',
        'Guyuk',
        'Hong',
        'Jada',
        'Lamurde',
        'Madagali',
        'Maiha',
        'Mayo-Belwa',
        'Michika',
        'Mubi North',
        'Mubi South',
        'Numan',
        'Shelleng',
        'Song',
        'Toungo',
        'Yola North',
        'Yola South'
    ],
    'Akwa Ibom' => [
        'Abak',
        'Eastern Obolo',
        'Eket',
        'Esit Eket',
        'Essien Udim',
        'Etim Ekpo',
        'Etinan',
        'Ibeno',
        'Ibesikpo Asutan',
        'Ibiono Ibom',
        'Ika',
        'Ikono',
        'Ikot Abasi',
        'Ikot Ekpene',
        'Ini',
        'Itu',
        'Mbo',
        'Mkpat Enin',
        'Nsit Atai',
        'Nsit Ibom',
        'Nsit Ubium',
        'Obot Akara',
        'Okobo',
        'Onna',
        'Oron',
        'Oruk Anam',
        'Ukanafun',
        'Udung Uko',
        'Uruan',
        'Urue-Offong/Oruko',
        'Uyo'
    ],
    'Anambra' => [
        'Aguata',
        'Anambra East',
        'Anambra West',
        'Anaocha',
        'Awka North',
        'Awka South',
        'Ayamelum',
        'Dunukofia',
        'Ekwusigo',
        'Idemili North',
        'Idemili South',
        'Ihiala',
        'Njikoka',
        'Nnewi North',
        'Nnewi South',
        'Ogbaru',
        'Onitsha North',
        'Onitsha South',
        'Orumba North',
        'Orumba South',
        'Oyi'
    ],
    'Bauchi' => [
        'Alkaleri',
        'Bauchi',
        'Bogoro',
        'Damban',
        'Darazo',
        'Dass',
        'Gamawa',
        'Ganjuwa',
        'Giade',
        'Itas/Gadau',
        'Jama’are',
        'Katagum',
        'Kirfi',
        'Misau',
        'Ningi',
        'Shira',
        'Tafawa Balewa',
        'Toro',
        'Warji',
        'Zaki'
    ],
    'Bayelsa' => [
        'Brass',
        'Ekeremor',
        'Kolokuma/Opokuma',
        'Nembe',
        'Ogbia',
        'Sagbama',
        'Southern Ijaw',
        'Yenagoa'
    ],
    'Benue' => [
        'Ado',
        'Agatu',
        'Apa',
        'Buruku',
        'Gboko',
        'Guma',
        'Gwer East',
        'Gwer West',
        'Katsina-Ala',
        'Konshisha',
        'Kwande',
        'Logo',
        'Makurdi',
        'Obi',
        'Ogbadibo',
        'Ohimini',
        'Oju',
        'Okpokwu',
        'Otukpo',
        'Tarka',
        'Ukum',
        'Ushongo',
        'Vandeikya'
    ],
    'Borno' => [
        'Abadam',
        'Askira/Uba',
        'Bama',
        'Bayo',
        'Biu',
        'Chibok',
        'Damboa',
        'Dikwa',
        'Gubio',
        'Guzamala',
        'Gwoza',
        'Hawul',
        'Jere',
        'Kaga',
        'Kala/Balge',
        'Konduga',
        'Kukawa',
        'Kwaya Kusar',
        'Mafa',
        'Magumeri',
        'Maiduguri',
        'Marte',
        'Mobbar',
        'Monguno',
        'Ngala',
        'Nganzai',
        'Shani'
    ],
    'Cross River' => [
        'Abi',
        'Akamkpa',
        'Akpabuyo',
        'Bakassi',
        'Bekwarra',
        'Biase',
        'Boki',
        'Calabar Municipal',
        'Calabar South',
        'Etung',
        'Ikom',
        'Obanliku',
        'Obubra',
        'Obudu',
        'Odukpani',
        'Ogoja',
        'Yakurr',
        'Yala'
    ],
    'Delta' => [
        'Aniocha North',
        'Aniocha South',
        'Bomadi',
        'Burutu',
        'Ethiope East',
        'Ethiope West',
        'Ika North East',
        'Ika South',
        'Isoko North',
        'Isoko South',
        'Ndokwa East',
        'Ndokwa West',
        'Okpe',
        'Oshimili North',
        'Oshimili South',
        'Patani',
        'Sapele',
        'Udu',
        'Ughelli North',
        'Ughelli South',
        'Ukwuani',
        'Uvwie',
        'Warri North',
        'Warri South',
        'Warri South West'
    ],
    'Ebonyi' => [
        'Abakaliki',
        'Afikpo North',
        'Afikpo South',
        'Ebonyi',
        'Ezza North',
        'Ezza South',
        'Ikwo',
        'Ishielu',
        'Ivo',
        'Izzi',
        'Ohaozara',
        'Ohaukwu',
        'Onicha'
    ],
    'Edo' => [
        'Akoko-Edo',
        'Egor',
        'Esan Central',
        'Esan South East',
        'Esan West',
        'Etsako Central',
        'Etsako East',
        'Etsako West',
        'Igueben',
        'Ikpoba-Okha',
        'Oredo',
        'Orhionmwon',
        'Ovia North East',
        'Ovia South West',
        'Owan East',
        'Owan West',
        'Uhunmwonde'
    ],
    'Ekiti' => [
        'Ado-Ekiti',
        'Efon',
        'Ekiti East',
        'Ekiti South West',
        'Ekiti West',
        'Emure',
        'Gbonyin',
        'Ido/Osi',
        'Ijero',
        'Ikere',
        'Ikole',
        'Ilejemeje',
        'Irepodun/Ifelodun',
        'Ise/Orun',
        'Moba',
        'Oye'
    ],
    'Enugu' => [
        'Aninri',
        'Awgu',
        'Enugu East',
        'Enugu North',
        'Enugu South',
        'Ezeagu',
        'Igbo Etiti',
        'Igbo Eze North',
        'Igbo Eze South',
        'Isi Uzo',
        'Nkanu East',
        'Nkanu West',
        'Nsukka',
        'Oji River',
        'Udenu',
        'Udi',
        'Uzo-Uwani'
    ],
    'Gombe' => [
        'Akko',
        'Balanga',
        'Billiri',
        'Dukku',
        'Funakaye',
        'Gombe',
        'Kaltungo',
        'Kwami',
        'Nafada',
        'Shongom',
        'Yamaltu/Deba'
    ],
    'Imo' => [
        'Aboh Mbaise',
        'Ahiazu Mbaise',
        'Ehime Mbano',
        'Ezinihitte Mbaise',
        'Ideato North',
        'Ideato South',
        'Ihitte/Uboma',
        'Ikeduru',
        'Isiala Mbano',
        'Isu',
        'Mbaitoli',
        'Ngor Okpala',
        'Njaba',
        'Nkwerre',
        'Nwangele',
        'Obowo',
        'Oguta',
        'Ohaji/Egbema',
        'Okigwe',
        'Onuimo',
        'Orlu',
        'Orsu',
        'Oru East',
        'Oru West',
        'Owerri Municipal',
        'Owerri North',
        'Owerri West'
    ],
    'Jigawa' => [
        'Auyo',
        'Babura',
        'Birnin Kudu',
        'Birniwa',
        'Buji',
        'Dutse',
        'Gagarawa',
        'Garki',
        'Gumel',
        'Guri',
        'Gwaram',
        'Gwiwa',
        'Hadejia',
        'Jahun',
        'Kafin Hausa',
        'Kaugama',
        'Kazaure',
        'Kiri Kasama',
        'Kiyawa',
        'Maigatari',
        'Malam Madori',
        'Miga',
        'Ringim',
        'Roni',
        'Sule Tankarkar',
        'Taura',
        'Yankwashi'
    ],
    'Kaduna' => [
        'Birnin Gwari',
        'Chikun',
        'Giwa',
        'Igabi',
        'Ikara',
        'Jaba',
        'Jema’a',
        'Kachia',
        'Kaduna North',
        'Kaduna South',
        'Kagarko',
        'Kajuru',
        'Kaura',
        'Kauru',
        'Kubau',
        'Kudan',
        'Lere',
        'Makarfi',
        'Sabon Gari',
        'Sanga',
        'Soba',
        'Zangon Kataf',
        'Zaria'
    ],
    'Kano' => [
        'Ajingi',
        'Albasu',
        'Bagwai',
        'Bebeji',
        'Bichi',
        'Bunkure',
        'Dala',
        'Dambatta',
        'Dawakin Kudu',
        'Dawakin Tofa',
        'Doguwa',
        'Fagge',
        'Gabasawa',
        'Garko',
        'Garun Mallam',
        'Gaya',
        'Gezawa',
        'Gwale',
        'Gwarzo',
        'Kabo',
        'Kano Municipal',
        'Karaye',
        'Kibiya',
        'Kiru',
        'Kumbotso',
        'Kunchi',
        'Kura',
        'Madobi',
        'Makoda',
        'Minjibir',
        'Nasarawa',
        'Rano',
        'Rimin Gado',
        'Rogo',
        'Shanono',
        'Sumaila',
        'Takai',
        'Tarauni',
        'Tofa',
        'Tsanyawa',
        'Tudun Wada',
        'Ungogo',
        'Warawa',
        'Wudil'
    ],
    'Katsina' => [
        'Bakori',
        'Batagarawa',
        'Batsari',
        'Baure',
        'Bindawa',
        'Charanchi',
        'Dandume',
        'Danja',
        'Dan Musa',
        'Daura',
        'Dutsi',
        'Dutsin Ma',
        'Faskari',
        'Funtua',
        'Ingawa',
        'Jibia',
        'Kafur',
        'Kaita',
        'Kankara',
        'Kankia',
        'Katsina',
        'Kurfi',
        'Kusada',
        'Mai’Adua',
        'Malumfashi',
        'Mani',
        'Mashi',
        'Matazu',
        'Musawa',
        'Rimi',
        'Sabuwa',
        'Safana',
        'Sandamu',
        'Zango'
    ],
    'Kebbi' => [
        'Aleiro',
        'Arewa Dandi',
        'Argungu',
        'Augie',
        'Bagudo',
        'Birnin Kebbi',
        'Bunza',
        'Dandi',
        'Fakai',
        'Gwandu',
        'Jega',
        'Kalgo',
        'Koko/Besse',
        'Maiyama',
        'Ngaski',
        'Sakaba',
        'Shanga',
        'Suru',
        'Wasagu/Danko',
        'Yauri',
        'Zuru'
    ],
    'Kogi' => [
        'Adavi',
        'Ajaokuta',
        'Ankpa',
        'Bassa',
        'Dekina',
        'Ibaji',
        'Idah',
        'Igalamela-Odolu',
        'Ijumu',
        'Kabba/Bunu',
        'Kogi',
        'Lokoja',
        'Mopa-Muro',
        'Ofu',
        'Ogori/Magongo',
        'Okehi',
        'Okene',
        'Olamaboro',
        'Omala',
        'Yagba East',
        'Yagba West'
    ],
    'Kwara' => [
        'Asa',
        'Baruten',
        'Edu',
        'Ekiti',
        'Ifelodun',
        'Ilorin East',
        'Ilorin South',
        'Ilorin West',
        'Irepodun',
        'Isin',
        'Kaiama',
        'Moro',
        'Offa',
        'Oke Ero',
        'Oyun',
        'Pategi'
    ],
    'Lagos' => [
        'Agege',
        'Ajeromi-Ifelodun',
        'Alimosho',
        'Amuwo-Odofin',
        'Apapa',
        'Badagry',
        'Epe',
        'Eti-Osa',
        'Ibeju-Lekki',
        'Ifako-Ijaiye',
        'Ikeja',
        'Ikorodu',
        'Kosofe',
        'Lagos Island',
        'Lagos Mainland',
        'Mushin',
        'Ojo',
        'Oshodi-Isolo',
        'Shomolu',
        'Surulere'
    ],
    'Nasarawa' => [
        'Akwanga',
        'Awe',
        'Doma',
        'Karu',
        'Keana',
        'Keffi',
        'Kokona',
        'Lafia',
        'Nasarawa',
        'Nasarawa Egon',
        'Obi',
        'Toto',
        'Wamba'
    ],
    'Niger' => [
        'Agaie',
        'Agwara',
        'Bida',
        'Borgu',
        'Bosso',
        'Chanchaga',
        'Edati',
        'Gbako',
        'Gurara',
        'Katcha',
        'Kontagora',
        'Lapai',
        'Lavun',
        'Magama',
        'Mariga',
        'Mashegu',
        'Mokwa',
        'Munya',
        'Paikoro',
        'Rafi',
        'Rijau',
        'Shiroro',
        'Suleja',
        'Tafa',
        'Wushishi'
    ],
    'Ogun' => [
        'Abeokuta North',
        'Abeokuta South',
        'Ado-Odo/Ota',
        'Egbado North',
        'Egbado South',
        'Ewekoro',
        'Ifo',
        'Ijebu East',
        'Ijebu North',
        'Ijebu North East',
        'Ijebu Ode',
        'Ikenne',
        'Imeko Afon',
        'Ipokia',
        'Obafemi Owode',
        'Odeda',
        'Odogbolu',
        'Ogun Waterside',
        'Remo North',
        'Shagamu'
    ],

    'Ondo' => [
        'Akoko North East',
        'Akoko North West',
        'Akoko South East',
        'Akoko South West',
        'Akure North',
        'Akure South',
        'Ese Odo',
        'Idanre',
        'Ifedore',
        'Ilaje',
        'Ile Oluji/Okeigbo',
        'Irele',
        'Odigbo',
        'Okitipupa',
        'Ondo East',
        'Ondo West',
        'Ose',
        'Owo'
    ],
    'Osun' => [
        'Aiyedaade',
        'Aiyedire',
        'Atakunmosa East',
        'Atakunmosa West',
        'Boluwaduro',
        'Boripe',
        'Ede North',
        'Ede South',
        'Egbedore',
        'Ejigbo',
        'Ife Central',
        'Ife East',
        'Ife North',
        'Ife South',
        'Ifedayo',
        'Ifelodun',
        'Ila',
        'Ilesa East',
        'Ilesa West',
        'Irepodun',
        'Irewole',
        'Isokan',
        'Iwo',
        'Obokun',
        'Odo Otin',
        'Ola Oluwa',
        'Olorunda',
        'Oriade',
        'Orolu',
        'Osogbo'
    ],
    'Oyo' => [
        'Afijio',
        'Akinyele',
        'Atiba',
        'Atisbo',
        'Egbeda',
        'Ibadan North',
        'Ibadan North East',
        'Ibadan North West',
        'Ibadan South East',
        'Ibadan South West',
        'Ibarapa Central',
        'Ibarapa East',
        'Ibarapa North',
        'Ido',
        'Irepo',
        'Iseyin',
        'Itesiwaju',
        'Iwajowa',
        'Kajola',
        'Lagelu',
        'Ogbomosho North',
        'Ogbomosho South',
        'Ogo Oluwa',
        'Olorunsogo',
        'Oluyole',
        'Ona Ara',
        'Orelope',
        'Ori Ire',
        'Oyo East',
        'Oyo West',
        'Saki East',
        'Saki West',
        'Surulere'
    ],
    'Plateau' => [
        'Barkin Ladi',
        'Bassa',
        'Bokkos',
        'Jos East',
        'Jos North',
        'Jos South',
        'Kanam',
        'Kanke',
        'Langtang North',
        'Langtang South',
        'Mangu',
        'Mikang',
        'Pankshin',
        'Qua’an Pan',
        'Riyom',
        'Shendam',
        'Wase'
    ],
    'Rivers' => [
        'Abua/Odual',
        'Ahoada East',
        'Ahoada West',
        'Akuku-Toru',
        'Andoni',
        'Asari-Toru',
        'Bonny',
        'Degema',
        'Eleme',
        'Emohua',
        'Etche',
        'Gokana',
        'Ikwerre',
        'Khana',
        'Obio/Akpor',
        'Ogba/Egbema/Ndoni',
        'Ogu/Bolo',
        'Okrika',
        'Omuma',
        'Opobo/Nkoro',
        'Oyigbo',
        'Port Harcourt',
        'Tai'
    ],
    'Sokoto' => [
        'Binji',
        'Bodinga',
        'Dange Shuni',
        'Gada',
        'Goronyo',
        'Gudu',
        'Gwadabawa',
        'Illela',
        'Isa',
        'Kebbe',
        'Kware',
        'Rabah',
        'Sabon Birni',
        'Shagari',
        'Silame',
        'Sokoto North',
        'Sokoto South',
        'Tambuwal',
        'Tangaza',
        'Tureta',
        'Wamako',
        'Wurno',
        'Yabo'
    ],
    'Taraba' => [
        'Ardo Kola',
        'Bali',
        'Donga',
        'Gashaka',
        'Gassol',
        'Ibi',
        'Jalingo',
        'Karim Lamido',
        'Kumi',
        'Lau',
        'Sardauna',
        'Takum',
        'Ussa',
        'Wukari',
        'Yorro',
        'Zing'
    ],
    'Yobe' => [
        'Bade',
        'Bursari',
        'Damaturu',
        'Fika',
        'Fune',
        'Geidam',
        'Gujba',
        'Gulani',
        'Jakusko',
        'Karasuwa',
        'Machina',
        'Nangere',
        'Nguru',
        'Potiskum',
        'Tarmuwa',
        'Yunusari',
        'Yusufari'
    ],
    'Zamfara' => [
        'Anka',
        'Bakura',
        'Birnin Magaji/Kiyaw',
        'Bukkuyum',
        'Bungudu',
        'Gummi',
        'Gusau',
        'Kaura Namoda',
        'Maradun',
        'Maru',
        'Shinkafi',
        'Talata Mafara',
        'Chafe',
        'Zurmi'
    ],
    'Federal Capital Territory (FCT)' => [
        'Abaji',
        'Bwari',
        'Gwagwalada',
        'Kuje',
        'Kwali',
        'Abuja Municipal'
     ]
    ];};
